USE [master]
GO
/****** Object:  Database [optimist]    Script Date: 12/1/2024 12:46:15 PM ******/
CREATE DATABASE [optimist]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'optimist', FILENAME = N'/var/opt/mssql/data/optimist.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'optimist_log', FILENAME = N'/var/opt/mssql/data/optimist_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [optimist] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [optimist].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [optimist] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [optimist] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [optimist] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [optimist] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [optimist] SET ARITHABORT OFF 
GO
ALTER DATABASE [optimist] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [optimist] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [optimist] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [optimist] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [optimist] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [optimist] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [optimist] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [optimist] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [optimist] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [optimist] SET  DISABLE_BROKER 
GO
ALTER DATABASE [optimist] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [optimist] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [optimist] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [optimist] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [optimist] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [optimist] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [optimist] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [optimist] SET RECOVERY FULL 
GO
ALTER DATABASE [optimist] SET  MULTI_USER 
GO
ALTER DATABASE [optimist] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [optimist] SET DB_CHAINING OFF 
GO
ALTER DATABASE [optimist] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [optimist] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [optimist] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [optimist] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'optimist', N'ON'
GO
ALTER DATABASE [optimist] SET QUERY_STORE = ON
GO
ALTER DATABASE [optimist] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [optimist]
GO
/****** Object:  Table [dbo].[Stuff]    Script Date: 12/1/2024 12:46:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Stuff](
	[StuffId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NULL,
	[Priority] [tinyint] NOT NULL,
	[RowVersion] [timestamp] NULL,
 CONSTRAINT [PK_Stuff] PRIMARY KEY CLUSTERED 
(
	[StuffId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Stuff] ADD  CONSTRAINT [DF_Stuff_Priority]  DEFAULT ((0)) FOR [Priority]
GO
USE [master]
GO
ALTER DATABASE [optimist] SET  READ_WRITE 
GO
Use [optimist]
go
SET IDENTITY_INSERT [optimist].[dbo].[Stuff] On

Insert Into [dbo].[Stuff] (StuffId, [Name], [Priority]) Values (1, 'A', 5);
Insert Into [dbo].[Stuff] (StuffId, [Name], [Priority]) Values (2, 'B', 4);
Insert Into [dbo].[Stuff] (StuffId, [Name], [Priority]) Values (3, 'C', 3);
Insert Into [dbo].[Stuff] (StuffId, [Name], [Priority]) Values (4, 'D', 2);
Insert Into [dbo].[Stuff] (StuffId, [Name], [Priority]) Values (5, 'E', 1);

SET IDENTITY_INSERT [optimist].[dbo].[Stuff] Off
GO
